parent=keycloak.v2
import=common/keycloak

styles=node_modules/patternfly/dist/css/patternfly.min.css node_modules/patternfly/dist/css/patternfly-additions.min.css lib/pficon/pficon.css css/login.css css/vneid-login.css

meta=viewport==width=device-width,initial-scale=1.0

locales=vi,en
